name: wt_geography_play
description: A new Flutter project.
publish_to: 'none'
version: 1.0.1+2

environment:
  sdk: '>=2.18.5 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_riverpod:
  freezed: ^2.3.0
  freezed_annotation: ^2.2.0
  geolocator: ^9.0.2
  firebase_core: ^2.4.0
  firebase_database: ^10.0.7
  wt_action_button:
    git:
      url: git@github.com:tmcmaster/wt_action_button.git
  wt_models:
    git:
      url: git@github.com:tmcmaster/wt_models.git
  wt_settings:
    git:
      url: git@github.com:tmcmaster/wt_settings.git
  wt_firepod:
    git:
      url: git@github.com:tmcmaster/wt_firepod.git
  wt_logging:
    git:
      url: git@github.com:tmcmaster/wt_logging.git
  wt_app_scaffold:
    git:
      url: https://github.com/tmcmaster/wt_app_scaffold.git
  point_in_polygon: ^1.0.0
  font_awesome_flutter:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.3.2
  flutter_native_splash: ^2.2.16
  flutter_launcher_icons: ^0.11.0
  json_serializable: ^6.5.4

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/data/

#dependency_overrides:
#  wt_app_scaffold:
#    path: ../wt_app_scaffold

flutter_icons:
  image_path: assets/wt_logo.png
  android: true
  ios: true

flutter_native_splash:
  color: "#9E9E9E"
  image: assets/wt_logo.png
  android_12:
  web_image_mode: center
