import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:wt_geography_play/models/country.dart';

final nameToCountryMapProvider = Provider<Map<String, Country>>((ref) {
  return {for (var c in ref.read(countryListProvider)) c.name: c};
});

final countryListProvider = Provider(
  name: "Country List",
  (ref) => [
    Country(id: "1", name: "Afghanistan"),
    Country(id: "2", name: "Angola"),
    Country(id: "3", name: "Albania"),
    Country(id: "4", name: "United Arab Emirates"),
    Country(id: "5", name: "Argentina"),
    Country(id: "6", name: "Armenia"),
    Country(id: "7", name: "Antarctica"),
    Country(id: "8", name: "French Southern and Antarctic Lands"),
    Country(id: "9", name: "Australia"),
    Country(id: "10", name: "Austria"),
    Country(id: "11", name: "Azerbaijan"),
    Country(id: "12", name: "Burundi"),
    Country(id: "13", name: "Belgium"),
    Country(id: "14", name: "Benin"),
    Country(id: "15", name: "Burkina Faso"),
    Country(id: "16", name: "Bangladesh"),
    Country(id: "17", name: "Bulgaria"),
    Country(id: "18", name: "The Bahamas"),
    Country(id: "19", name: "Bosnia and Herzegovina"),
    Country(id: "20", name: "Belarus"),
    Country(id: "21", name: "Belize"),
    Country(id: "22", name: "Bolivia"),
    Country(id: "23", name: "Brazil"),
    Country(id: "24", name: "Brunei"),
    Country(id: "25", name: "Bhutan"),
    Country(id: "26", name: "Botswana"),
    Country(id: "27", name: "Central African Republic"),
    Country(id: "28", name: "Canada"),
    Country(id: "29", name: "Switzerland"),
    Country(id: "30", name: "Chile"),
    Country(id: "31", name: "China"),
    Country(id: "32", name: "Ivory Coast"),
    Country(id: "33", name: "Cameroon"),
    Country(id: "34", name: "Democratic Republic of the Congo"),
    Country(id: "35", name: "Republic of the Congo"),
    Country(id: "36", name: "Colombia"),
    Country(id: "37", name: "Costa Rica"),
    Country(id: "38", name: "Cuba"),
    Country(id: "39", name: "Northern Cyprus"),
    Country(id: "40", name: "Cyprus"),
    Country(id: "41", name: "Czech Republic"),
    Country(id: "42", name: "Germany"),
    Country(id: "43", name: "Djibouti"),
    Country(id: "44", name: "Denmark"),
    Country(id: "45", name: "Dominican Republic"),
    Country(id: "46", name: "Algeria"),
    Country(id: "47", name: "Ecuador"),
    Country(id: "48", name: "Egypt"),
    Country(id: "49", name: "Eritrea"),
    Country(id: "50", name: "Spain"),
    Country(id: "51", name: "Estonia"),
    Country(id: "52", name: "Ethiopia"),
    Country(id: "53", name: "Finland"),
    Country(id: "54", name: "Fiji"),
    Country(id: "55", name: "Falkland Islands"),
    Country(id: "56", name: "France"),
    Country(id: "57", name: "Gabon"),
    Country(id: "58", name: "England"),
    Country(id: "59", name: "Georgia"),
    Country(id: "60", name: "Ghana"),
    Country(id: "61", name: "Guinea"),
    Country(id: "62", name: "Gambia"),
    Country(id: "63", name: "Guinea Bissau"),
    Country(id: "64", name: "Equatorial Guinea"),
    Country(id: "65", name: "Greece"),
    Country(id: "66", name: "Greenland"),
    Country(id: "67", name: "Guatemala"),
    Country(id: "68", name: "Guyana"),
    Country(id: "69", name: "Honduras"),
    Country(id: "70", name: "Croatia"),
    Country(id: "71", name: "Haiti"),
    Country(id: "72", name: "Hungary"),
    Country(id: "73", name: "Indonesia"),
    Country(id: "74", name: "India"),
    Country(id: "75", name: "Ireland"),
    Country(id: "76", name: "Iran"),
    Country(id: "77", name: "Iraq"),
    Country(id: "78", name: "Iceland"),
    Country(id: "79", name: "Israel"),
    Country(id: "80", name: "Italy"),
    Country(id: "81", name: "Jamaica"),
    Country(id: "82", name: "Jordan"),
    Country(id: "83", name: "Japan"),
    Country(id: "84", name: "Kazakhstan"),
    Country(id: "85", name: "Kenya"),
    Country(id: "86", name: "Kyrgyzstan"),
    Country(id: "87", name: "Cambodia"),
    Country(id: "88", name: "South Korea"),
    Country(id: "89", name: "Kosovo"),
    Country(id: "90", name: "Kuwait"),
    Country(id: "91", name: "Laos"),
    Country(id: "92", name: "Lebanon"),
    Country(id: "93", name: "Liberia"),
    Country(id: "94", name: "Libya"),
    Country(id: "95", name: "Sri Lanka"),
    Country(id: "96", name: "Lesotho"),
    Country(id: "97", name: "Lithuania"),
    Country(id: "98", name: "Luxembourg"),
    Country(id: "99", name: "Latvia"),
    Country(id: "100", name: "Morocco"),
    Country(id: "101", name: "Moldova"),
    Country(id: "102", name: "Madagascar"),
    Country(id: "103", name: "Mexico"),
    Country(id: "104", name: "Macedonia"),
    Country(id: "105", name: "Mali"),
    Country(id: "106", name: "Myanmar"),
    Country(id: "107", name: "Montenegro"),
    Country(id: "108", name: "Mongolia"),
    Country(id: "109", name: "Mozambique"),
    Country(id: "110", name: "Mauritania"),
    Country(id: "111", name: "Malawi"),
    Country(id: "112", name: "Malaysia"),
    Country(id: "113", name: "Namibia"),
    Country(id: "114", name: "New Caledonia"),
    Country(id: "115", name: "Niger"),
    Country(id: "116", name: "Nigeria"),
    Country(id: "117", name: "Nicaragua"),
    Country(id: "118", name: "Netherlands"),
    Country(id: "119", name: "Norway"),
    Country(id: "120", name: "Nepal"),
    Country(id: "121", name: "New Zealand"),
    Country(id: "122", name: "Oman"),
    Country(id: "123", name: "Pakistan"),
    Country(id: "124", name: "Panama"),
    Country(id: "125", name: "Peru"),
    Country(id: "126", name: "Philippines"),
    Country(id: "127", name: "Papua New Guinea"),
    Country(id: "128", name: "Poland"),
    Country(id: "129", name: "Puerto Rico"),
    Country(id: "130", name: "North Korea"),
    Country(id: "131", name: "Portugal"),
    Country(id: "132", name: "Paraguay"),
    Country(id: "133", name: "Qatar"),
    Country(id: "134", name: "Romania"),
    Country(id: "135", name: "Russia"),
    Country(id: "136", name: "Rwanda"),
    Country(id: "137", name: "Western Sahara"),
    Country(id: "138", name: "Saudi Arabia"),
    Country(id: "139", name: "Sudan"),
    Country(id: "140", name: "South Sudan"),
    Country(id: "141", name: "Senegal"),
    Country(id: "142", name: "Solomon Islands"),
    Country(id: "143", name: "Sierra Leone"),
    Country(id: "144", name: "El Salvador"),
    Country(id: "145", name: "Somaliland"),
    Country(id: "146", name: "Somalia"),
    Country(id: "147", name: "Republic of Serbia"),
    Country(id: "148", name: "Suriname"),
    Country(id: "149", name: "Slovakia"),
    Country(id: "150", name: "Slovenia"),
    Country(id: "151", name: "Sweden"),
    Country(id: "152", name: "Swaziland"),
    Country(id: "153", name: "Syria"),
    Country(id: "154", name: "Chad"),
    Country(id: "155", name: "Togo"),
    Country(id: "156", name: "Thailand"),
    Country(id: "157", name: "Tajikistan"),
    Country(id: "158", name: "Turkmenistan"),
    Country(id: "159", name: "East Timor"),
    Country(id: "160", name: "Trinidad and Tobago"),
    Country(id: "161", name: "Tunisia"),
    Country(id: "162", name: "Turkey"),
    Country(id: "163", name: "Taiwan"),
    Country(id: "164", name: "United Republic of Tanzania"),
    Country(id: "165", name: "Uganda"),
    Country(id: "166", name: "Ukraine"),
    Country(id: "167", name: "Uruguay"),
    Country(id: "168", name: "USA"),
    Country(id: "169", name: "Uzbekistan"),
    Country(id: "170", name: "Venezuela"),
    Country(id: "171", name: "Vietnam"),
    Country(id: "172", name: "Vanuatu"),
    Country(id: "173", name: "West Bank"),
    Country(id: "174", name: "Yemen"),
    Country(id: "175", name: "South Africa"),
    Country(id: "176", name: "Zambia"),
    Country(id: "177", name: "Zimbabwe"),
  ],
);
