import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:wt_geography_play/models/country.dart';

final countriesProvider = Provider<Map<String, Country>>((ref) => {
      "Afghanistan": Country(
          id: "1",
          name: "Afghanistan",
          capital: "Kabul",
          longitude: 69.183333,
          latitude: 34.516666666666666,
          code: "AF",
          continent: "Asia"),
      "Aland Islands": Country(
          id: "2",
          name: "Aland Islands",
          capital: "Mariehamn",
          longitude: 19.9,
          latitude: 60.116667,
          code: "AX",
          continent: "Europe"),
      "Albania": Country(
          id: "3",
          name: "Albania",
          capital: "Tirana",
          longitude: 19.816667,
          latitude: 41.31666666666667,
          code: "AL",
          continent: "Europe"),
      "Algeria": Country(
          id: "4",
          name: "Algeria",
          capital: "Algiers",
          longitude: 3.05,
          latitude: 36.75,
          code: "DZ",
          continent: "Africa"),
      "American Samoa": Country(
          id: "5",
          name: "American Samoa",
          capital: "Pago Pago",
          longitude: -170.7,
          latitude: -14.266666666666667,
          code: "AS",
          continent: "Australia"),
      "Andorra": Country(
          id: "6",
          name: "Andorra",
          capital: "Andorra la Vella",
          longitude: 1.516667,
          latitude: 42.5,
          code: "AD",
          continent: "Europe"),
      "Angola": Country(
          id: "7",
          name: "Angola",
          capital: "Luanda",
          longitude: 13.216667,
          latitude: -8.833333333333334,
          code: "AO",
          continent: "Africa"),
      "Anguilla": Country(
          id: "8",
          name: "Anguilla",
          capital: "The Valley",
          longitude: -63.05,
          latitude: 18.216666666666665,
          code: "AI",
          continent: "North America"),
      "Antarctica": Country(
          id: "9",
          name: "Antarctica",
          capital: "N/A",
          longitude: 0.0,
          latitude: 0,
          code: "AQ",
          continent: "Antarctica"),
      "Antigua and Barbuda": Country(
          id: "10",
          name: "Antigua and Barbuda",
          capital: "Saint John's",
          longitude: -61.85,
          latitude: 17.116666666666667,
          code: "AG",
          continent: "North America"),
      "Argentina": Country(
          id: "11",
          name: "Argentina",
          capital: "Buenos Aires",
          longitude: -58.666667,
          latitude: -34.583333333333336,
          code: "AR",
          continent: "South America"),
      "Armenia": Country(
          id: "12",
          name: "Armenia",
          capital: "Yerevan",
          longitude: 44.5,
          latitude: 40.166666666666664,
          code: "AM",
          continent: "Europe"),
      "Aruba": Country(
          id: "13",
          name: "Aruba",
          capital: "Oranjestad",
          longitude: -70.033333,
          latitude: 12.516666666666667,
          code: "AW",
          continent: "North America"),
      "Australia": Country(
          id: "14",
          name: "Australia",
          capital: "Canberra",
          longitude: 149.133333,
          latitude: -35.266666666666666,
          code: "AU",
          continent: "Australia"),
      "Austria": Country(
          id: "15",
          name: "Austria",
          capital: "Vienna",
          longitude: 16.366667,
          latitude: 48.2,
          code: "AT",
          continent: "Europe"),
      "Azerbaijan": Country(
          id: "16",
          name: "Azerbaijan",
          capital: "Baku",
          longitude: 49.866667,
          latitude: 40.38333333333333,
          code: "AZ",
          continent: "Europe"),
      "Bahamas": Country(
          id: "17",
          name: "Bahamas",
          capital: "Nassau",
          longitude: -77.35,
          latitude: 25.083333333333332,
          code: "BS",
          continent: "North America"),
      "Bahrain": Country(
          id: "18",
          name: "Bahrain",
          capital: "Manama",
          longitude: 50.566667,
          latitude: 26.233333333333334,
          code: "BH",
          continent: "Asia"),
      "Bangladesh": Country(
          id: "19",
          name: "Bangladesh",
          capital: "Dhaka",
          longitude: 90.4,
          latitude: 23.716666666666665,
          code: "BD",
          continent: "Asia"),
      "Barbados": Country(
          id: "20",
          name: "Barbados",
          capital: "Bridgetown",
          longitude: -59.616667,
          latitude: 13.1,
          code: "BB",
          continent: "North America"),
      "Belarus": Country(
          id: "21",
          name: "Belarus",
          capital: "Minsk",
          longitude: 27.566667,
          latitude: 53.9,
          code: "BY",
          continent: "Europe"),
      "Belgium": Country(
          id: "22",
          name: "Belgium",
          capital: "Brussels",
          longitude: 4.333333,
          latitude: 50.833333333333336,
          code: "BE",
          continent: "Europe"),
      "Belize": Country(
          id: "23",
          name: "Belize",
          capital: "Belmopan",
          longitude: -88.766667,
          latitude: 17.25,
          code: "BZ",
          continent: "Central America"),
      "Benin": Country(
          id: "24",
          name: "Benin",
          capital: "Porto-Novo",
          longitude: 2.616667,
          latitude: 6.483333333333333,
          code: "BJ",
          continent: "Africa"),
      "Bermuda": Country(
          id: "25",
          name: "Bermuda",
          capital: "Hamilton",
          longitude: -64.783333,
          latitude: 32.28333333333333,
          code: "BM",
          continent: "North America"),
      "Bhutan": Country(
          id: "26",
          name: "Bhutan",
          capital: "Thimphu",
          longitude: 89.633333,
          latitude: 27.466666666666665,
          code: "BT",
          continent: "Asia"),
      "Bolivia": Country(
          id: "27",
          name: "Bolivia",
          capital: "La Paz",
          longitude: -68.15,
          latitude: -16.5,
          code: "BO",
          continent: "South America"),
      "Bosnia and Herzegovina": Country(
          id: "28",
          name: "Bosnia and Herzegovina",
          capital: "Sarajevo",
          longitude: 18.416667,
          latitude: 43.86666666666667,
          code: "BA",
          continent: "Europe"),
      "Botswana": Country(
          id: "29",
          name: "Botswana",
          capital: "Gaborone",
          longitude: 25.9,
          latitude: -24.633333333333333,
          code: "BW",
          continent: "Africa"),
      "Brazil": Country(
          id: "30",
          name: "Brazil",
          capital: "Brasilia",
          longitude: -47.916667,
          latitude: -15.783333333333333,
          code: "BR",
          continent: "South America"),
      "British Indian Ocean Territory": Country(
          id: "31",
          name: "British Indian Ocean Territory",
          capital: "Diego Garcia",
          longitude: 72.4,
          latitude: -7.3,
          code: "IO",
          continent: "Africa"),
      "British Virgin Islands": Country(
          id: "32",
          name: "British Virgin Islands",
          capital: "Road Town",
          longitude: -64.616667,
          latitude: 18.416666666666668,
          code: "VG",
          continent: "North America"),
      "Brunei Darussalam": Country(
          id: "33",
          name: "Brunei Darussalam",
          capital: "Bandar Seri Begawan",
          longitude: 114.933333,
          latitude: 4.883333333333333,
          code: "BN",
          continent: "Asia"),
      "Bulgaria": Country(
          id: "34",
          name: "Bulgaria",
          capital: "Sofia",
          longitude: 23.316667,
          latitude: 42.68333333333333,
          code: "BG",
          continent: "Europe"),
      "Burkina Faso": Country(
          id: "35",
          name: "Burkina Faso",
          capital: "Ouagadougou",
          longitude: -1.516667,
          latitude: 12.366666666666667,
          code: "BF",
          continent: "Africa"),
      "Burundi": Country(
          id: "36",
          name: "Burundi",
          capital: "Bujumbura",
          longitude: 29.35,
          latitude: -3.3666666666666667,
          code: "BI",
          continent: "Africa"),
      "Cambodia": Country(
          id: "37",
          name: "Cambodia",
          capital: "Phnom Penh",
          longitude: 104.916667,
          latitude: 11.55,
          code: "KH",
          continent: "Asia"),
      "Cameroon": Country(
          id: "38",
          name: "Cameroon",
          capital: "Yaounde",
          longitude: 11.516667,
          latitude: 3.8666666666666667,
          code: "CM",
          continent: "Africa"),
      "Canada": Country(
          id: "39",
          name: "Canada",
          capital: "Ottawa",
          longitude: -75.7,
          latitude: 45.416666666666664,
          code: "CA",
          continent: "Central America"),
      "Cape Verde": Country(
          id: "40",
          name: "Cape Verde",
          capital: "Praia",
          longitude: -23.516667,
          latitude: 14.916666666666666,
          code: "CV",
          continent: "Africa"),
      "Cayman Islands": Country(
          id: "41",
          name: "Cayman Islands",
          capital: "George Town",
          longitude: -81.383333,
          latitude: 19.3,
          code: "KY",
          continent: "North America"),
      "Central African Republic": Country(
          id: "42",
          name: "Central African Republic",
          capital: "Bangui",
          longitude: 18.583333,
          latitude: 4.366666666666666,
          code: "CF",
          continent: "Africa"),
      "Chad": Country(
          id: "43",
          name: "Chad",
          capital: "N'Djamena",
          longitude: 15.033333,
          latitude: 12.1,
          code: "TD",
          continent: "Africa"),
      "Chile": Country(
          id: "44",
          name: "Chile",
          capital: "Santiago",
          longitude: -70.666667,
          latitude: -33.45,
          code: "CL",
          continent: "South America"),
      "China": Country(
          id: "45",
          name: "China",
          capital: "Beijing",
          longitude: 116.383333,
          latitude: 39.916666666666664,
          code: "CN",
          continent: "Asia"),
      "Christmas Island": Country(
          id: "46",
          name: "Christmas Island",
          capital: "The Settlement",
          longitude: 105.716667,
          latitude: -10.416666666666666,
          code: "CX",
          continent: "Australia"),
      "Cocos Islands": Country(
          id: "47",
          name: "Cocos Islands",
          capital: "West Island",
          longitude: 96.833333,
          latitude: -12.166666666666666,
          code: "CC",
          continent: "Australia"),
      "Colombia": Country(
          id: "48",
          name: "Colombia",
          capital: "Bogota",
          longitude: -74.083333,
          latitude: 4.6,
          code: "CO",
          continent: "South America"),
      "Comoros": Country(
          id: "49",
          name: "Comoros",
          capital: "Moroni",
          longitude: 43.233333,
          latitude: -11.7,
          code: "KM",
          continent: "Africa"),
      "Cook Islands": Country(
          id: "50",
          name: "Cook Islands",
          capital: "Avarua",
          longitude: -159.766667,
          latitude: -21.2,
          code: "CK",
          continent: "Australia"),
      "Costa Rica": Country(
          id: "51",
          name: "Costa Rica",
          capital: "San Jose",
          longitude: -84.083333,
          latitude: 9.933333333333334,
          code: "CR",
          continent: "Central America"),
      "Cote d'Ivoire": Country(
          id: "52",
          name: "Cote d'Ivoire",
          capital: "Yamoussoukro",
          longitude: -5.266667,
          latitude: 6.816666666666666,
          code: "CI",
          continent: "Africa"),
      "Croatia": Country(
          id: "53",
          name: "Croatia",
          capital: "Zagreb",
          longitude: 16.0,
          latitude: 45.8,
          code: "HR",
          continent: "Europe"),
      "Cuba": Country(
          id: "54",
          name: "Cuba",
          capital: "Havana",
          longitude: -82.35,
          latitude: 23.116666666666667,
          code: "CU",
          continent: "North America"),
      "CuraÃ§ao": Country(
          id: "55",
          name: "CuraÃ§ao",
          capital: "Willemstad",
          longitude: -68.916667,
          latitude: 12.1,
          code: "CW",
          continent: "North America"),
      "Cyprus": Country(
          id: "56",
          name: "Cyprus",
          capital: "Nicosia",
          longitude: 33.366667,
          latitude: 35.166666666666664,
          code: "CY",
          continent: "Europe"),
      "Czech Republic": Country(
          id: "57",
          name: "Czech Republic",
          capital: "Prague",
          longitude: 14.466667,
          latitude: 50.083333333333336,
          code: "CZ",
          continent: "Europe"),
      "Democratic Republic of the Congo": Country(
          id: "58",
          name: "Democratic Republic of the Congo",
          capital: "Kinshasa",
          longitude: 15.3,
          latitude: -4.316666666666666,
          code: "CD",
          continent: "Africa"),
      "Denmark": Country(
          id: "59",
          name: "Denmark",
          capital: "Copenhagen",
          longitude: 12.583333,
          latitude: 55.666666666666664,
          code: "DK",
          continent: "Europe"),
      "Djibouti": Country(
          id: "60",
          name: "Djibouti",
          capital: "Djibouti",
          longitude: 43.15,
          latitude: 11.583333333333334,
          code: "DJ",
          continent: "Africa"),
      "Dominica": Country(
          id: "61",
          name: "Dominica",
          capital: "Roseau",
          longitude: -61.4,
          latitude: 15.3,
          code: "DM",
          continent: "North America"),
      "Dominican Republic": Country(
          id: "62",
          name: "Dominican Republic",
          capital: "Santo Domingo",
          longitude: -69.9,
          latitude: 18.466666666666665,
          code: "DO",
          continent: "North America"),
      "Ecuador": Country(
          id: "63",
          name: "Ecuador",
          capital: "Quito",
          longitude: -78.5,
          latitude: -0.21666666666666667,
          code: "EC",
          continent: "South America"),
      "Egypt": Country(
          id: "64",
          name: "Egypt",
          capital: "Cairo",
          longitude: 31.25,
          latitude: 30.05,
          code: "EG",
          continent: "Africa"),
      "El Salvador": Country(
          id: "65",
          name: "El Salvador",
          capital: "San Salvador",
          longitude: -89.2,
          latitude: 13.7,
          code: "SV",
          continent: "Central America"),
      "Equatorial Guinea": Country(
          id: "66",
          name: "Equatorial Guinea",
          capital: "Malabo",
          longitude: 8.783333,
          latitude: 3.75,
          code: "GQ",
          continent: "Africa"),
      "Eritrea": Country(
          id: "67",
          name: "Eritrea",
          capital: "Asmara",
          longitude: 38.933333,
          latitude: 15.333333333333334,
          code: "ER",
          continent: "Africa"),
      "Estonia": Country(
          id: "68",
          name: "Estonia",
          capital: "Tallinn",
          longitude: 24.716667,
          latitude: 59.43333333333333,
          code: "EE",
          continent: "Europe"),
      "Ethiopia": Country(
          id: "69",
          name: "Ethiopia",
          capital: "Addis Ababa",
          longitude: 38.7,
          latitude: 9.033333333333333,
          code: "ET",
          continent: "Africa"),
      "Falkland Islands": Country(
          id: "70",
          name: "Falkland Islands",
          capital: "Stanley",
          longitude: -57.85,
          latitude: -51.7,
          code: "FK",
          continent: "South America"),
      "Faroe Islands": Country(
          id: "71",
          name: "Faroe Islands",
          capital: "Torshavn",
          longitude: -6.766667,
          latitude: 62,
          code: "FO",
          continent: "Europe"),
      "Federated States of Micronesia": Country(
          id: "72",
          name: "Federated States of Micronesia",
          capital: "Palikir",
          longitude: 158.15,
          latitude: 6.916666666666667,
          code: "FM",
          continent: "Australia"),
      "Fiji": Country(
          id: "73",
          name: "Fiji",
          capital: "Suva",
          longitude: 178.416667,
          latitude: -18.133333333333333,
          code: "FJ",
          continent: "Australia"),
      "Finland": Country(
          id: "74",
          name: "Finland",
          capital: "Helsinki",
          longitude: 24.933333,
          latitude: 60.166666666666664,
          code: "FI",
          continent: "Europe"),
      "France": Country(
          id: "75",
          name: "France",
          capital: "Paris",
          longitude: 2.333333,
          latitude: 48.86666666666667,
          code: "FR",
          continent: "Europe"),
      "French Polynesia": Country(
          id: "76",
          name: "French Polynesia",
          capital: "Papeete",
          longitude: -149.566667,
          latitude: -17.533333333333335,
          code: "PF",
          continent: "Australia"),
      "French Southern and Antarctic Lands": Country(
          id: "77",
          name: "French Southern and Antarctic Lands",
          capital: "Port-aux-FranÃ§ais",
          longitude: 70.216667,
          latitude: -49.35,
          code: "TF",
          continent: "Antarctica"),
      "Gabon": Country(
          id: "78",
          name: "Gabon",
          capital: "Libreville",
          longitude: 9.45,
          latitude: 0.38333333333333336,
          code: "GA",
          continent: "Africa"),
      "Georgia": Country(
          id: "79",
          name: "Georgia",
          capital: "Tbilisi",
          longitude: 44.833333,
          latitude: 41.68333333333333,
          code: "GE",
          continent: "Europe"),
      "Germany": Country(
          id: "80",
          name: "Germany",
          capital: "Berlin",
          longitude: 13.4,
          latitude: 52.516666666666666,
          code: "DE",
          continent: "Europe"),
      "Ghana": Country(
          id: "81",
          name: "Ghana",
          capital: "Accra",
          longitude: -0.216667,
          latitude: 5.55,
          code: "GH",
          continent: "Africa"),
      "Gibraltar": Country(
          id: "82",
          name: "Gibraltar",
          capital: "Gibraltar",
          longitude: -5.35,
          latitude: 36.13333333333333,
          code: "GI",
          continent: "Europe"),
      "Greece": Country(
          id: "83",
          name: "Greece",
          capital: "Athens",
          longitude: 23.733333,
          latitude: 37.983333333333334,
          code: "GR",
          continent: "Europe"),
      "Greenland": Country(
          id: "84",
          name: "Greenland",
          capital: "Nuuk",
          longitude: -51.75,
          latitude: 64.18333333333334,
          code: "GL",
          continent: "Central America"),
      "Grenada": Country(
          id: "85",
          name: "Grenada",
          capital: "Saint George's",
          longitude: -61.75,
          latitude: 12.05,
          code: "GD",
          continent: "North America"),
      "Guam": Country(
          id: "86",
          name: "Guam",
          capital: "Hagatna",
          longitude: 144.733333,
          latitude: 13.466666666666667,
          code: "GU",
          continent: "Australia"),
      "Guatemala": Country(
          id: "87",
          name: "Guatemala",
          capital: "Guatemala City",
          longitude: -90.516667,
          latitude: 14.616666666666667,
          code: "GT",
          continent: "Central America"),
      "Guernsey": Country(
          id: "88",
          name: "Guernsey",
          capital: "Saint Peter Port",
          longitude: -2.533333,
          latitude: 49.45,
          code: "GG",
          continent: "Europe"),
      "Guinea": Country(
          id: "89",
          name: "Guinea",
          capital: "Conakry",
          longitude: -13.7,
          latitude: 9.5,
          code: "GN",
          continent: "Africa"),
      "Guinea-Bissau": Country(
          id: "90",
          name: "Guinea-Bissau",
          capital: "Bissau",
          longitude: -15.583333,
          latitude: 11.85,
          code: "GW",
          continent: "Africa"),
      "Guyana": Country(
          id: "91",
          name: "Guyana",
          capital: "Georgetown",
          longitude: -58.15,
          latitude: 6.8,
          code: "GY",
          continent: "South America"),
      "Haiti": Country(
          id: "92",
          name: "Haiti",
          capital: "Port-au-Prince",
          longitude: -72.333333,
          latitude: 18.533333333333335,
          code: "HT",
          continent: "North America"),
      "Heard Island and McDonald Islands": Country(
          id: "93",
          name: "Heard Island and McDonald Islands",
          capital: "N/A",
          longitude: 0.0,
          latitude: 0,
          code: "HM",
          continent: "Antarctica"),
      "Honduras": Country(
          id: "94",
          name: "Honduras",
          capital: "Tegucigalpa",
          longitude: -87.216667,
          latitude: 14.1,
          code: "HN",
          continent: "Central America"),
      "Hong Kong": Country(
          id: "95",
          name: "Hong Kong",
          capital: "N/A",
          longitude: 0.0,
          latitude: 0,
          code: "HK",
          continent: "Asia"),
      "Hungary": Country(
          id: "96",
          name: "Hungary",
          capital: "Budapest",
          longitude: 19.083333,
          latitude: 47.5,
          code: "HU",
          continent: "Europe"),
      "Iceland": Country(
          id: "97",
          name: "Iceland",
          capital: "Reykjavik",
          longitude: -21.95,
          latitude: 64.15,
          code: "IS",
          continent: "Europe"),
      "India": Country(
          id: "98",
          name: "India",
          capital: "New Delhi",
          longitude: 77.2,
          latitude: 28.6,
          code: "IN",
          continent: "Asia"),
      "Indonesia": Country(
          id: "99",
          name: "Indonesia",
          capital: "Jakarta",
          longitude: 106.816667,
          latitude: -6.166666666666667,
          code: "ID",
          continent: "Asia"),
      "Iran": Country(
          id: "100",
          name: "Iran",
          capital: "Tehran",
          longitude: 51.416667,
          latitude: 35.7,
          code: "IR",
          continent: "Asia"),
      "Iraq": Country(
          id: "101",
          name: "Iraq",
          capital: "Baghdad",
          longitude: 44.4,
          latitude: 33.333333333333336,
          code: "IQ",
          continent: "Asia"),
      "Ireland": Country(
          id: "102",
          name: "Ireland",
          capital: "Dublin",
          longitude: -6.233333,
          latitude: 53.31666666666667,
          code: "IE",
          continent: "Europe"),
      "Isle of Man": Country(
          id: "103",
          name: "Isle of Man",
          capital: "Douglas",
          longitude: -4.483333,
          latitude: 54.15,
          code: "IM",
          continent: "Europe"),
      "Israel": Country(
          id: "104",
          name: "Israel",
          capital: "Jerusalem",
          longitude: 35.233333,
          latitude: 31.766666666666666,
          code: "IL",
          continent: "Asia"),
      "Italy": Country(
          id: "105",
          name: "Italy",
          capital: "Rome",
          longitude: 12.483333,
          latitude: 41.9,
          code: "IT",
          continent: "Europe"),
      "Jamaica": Country(
          id: "106",
          name: "Jamaica",
          capital: "Kingston",
          longitude: -76.8,
          latitude: 18,
          code: "JM",
          continent: "North America"),
      "Japan": Country(
          id: "107",
          name: "Japan",
          capital: "Tokyo",
          longitude: 139.75,
          latitude: 35.68333333333333,
          code: "JP",
          continent: "Asia"),
      "Jersey": Country(
          id: "108",
          name: "Jersey",
          capital: "Saint Helier",
          longitude: -2.1,
          latitude: 49.18333333333333,
          code: "JE",
          continent: "Europe"),
      "Jordan": Country(
          id: "109",
          name: "Jordan",
          capital: "Amman",
          longitude: 35.933333,
          latitude: 31.95,
          code: "JO",
          continent: "Asia"),
      "Kazakhstan": Country(
          id: "110",
          name: "Kazakhstan",
          capital: "Astana",
          longitude: 71.416667,
          latitude: 51.166666666666664,
          code: "KZ",
          continent: "Asia"),
      "Kenya": Country(
          id: "111",
          name: "Kenya",
          capital: "Nairobi",
          longitude: 36.816667,
          latitude: -1.2833333333333332,
          code: "KE",
          continent: "Africa"),
      "Kiribati": Country(
          id: "112",
          name: "Kiribati",
          capital: "Tarawa",
          longitude: 169.533333,
          latitude: -0.8833333333333333,
          code: "KI",
          continent: "Australia"),
      "Kosovo": Country(
          id: "113",
          name: "Kosovo",
          capital: "Pristina",
          longitude: 21.166667,
          latitude: 42.666666666666664,
          code: "KO",
          continent: "Europe"),
      "Kuwait": Country(
          id: "114",
          name: "Kuwait",
          capital: "Kuwait City",
          longitude: 47.966667,
          latitude: 29.366666666666667,
          code: "KW",
          continent: "Asia"),
      "Kyrgyzstan": Country(
          id: "115",
          name: "Kyrgyzstan",
          capital: "Bishkek",
          longitude: 74.6,
          latitude: 42.86666666666667,
          code: "KG",
          continent: "Asia"),
      "Laos": Country(
          id: "116",
          name: "Laos",
          capital: "Vientiane",
          longitude: 102.6,
          latitude: 17.966666666666665,
          code: "LA",
          continent: "Asia"),
      "Latvia": Country(
          id: "117",
          name: "Latvia",
          capital: "Riga",
          longitude: 24.1,
          latitude: 56.95,
          code: "LV",
          continent: "Europe"),
      "Lebanon": Country(
          id: "118",
          name: "Lebanon",
          capital: "Beirut",
          longitude: 35.5,
          latitude: 33.86666666666667,
          code: "LB",
          continent: "Asia"),
      "Lesotho": Country(
          id: "119",
          name: "Lesotho",
          capital: "Maseru",
          longitude: 27.483333,
          latitude: -29.316666666666666,
          code: "LS",
          continent: "Africa"),
      "Liberia": Country(
          id: "120",
          name: "Liberia",
          capital: "Monrovia",
          longitude: -10.8,
          latitude: 6.3,
          code: "LR",
          continent: "Africa"),
      "Libya": Country(
          id: "121",
          name: "Libya",
          capital: "Tripoli",
          longitude: 13.166667,
          latitude: 32.88333333333333,
          code: "LY",
          continent: "Africa"),
      "Liechtenstein": Country(
          id: "122",
          name: "Liechtenstein",
          capital: "Vaduz",
          longitude: 9.516667,
          latitude: 47.13333333333333,
          code: "LI",
          continent: "Europe"),
      "Lithuania": Country(
          id: "123",
          name: "Lithuania",
          capital: "Vilnius",
          longitude: 25.316667,
          latitude: 54.68333333333333,
          code: "LT",
          continent: "Europe"),
      "Luxembourg": Country(
          id: "124",
          name: "Luxembourg",
          capital: "Luxembourg",
          longitude: 6.116667,
          latitude: 49.6,
          code: "LU",
          continent: "Europe"),
      "Macau": Country(
          id: "125",
          name: "Macau",
          capital: "N/A",
          longitude: 0.0,
          latitude: 0,
          code: "MO",
          continent: "Asia"),
      "Macedonia": Country(
          id: "126",
          name: "Macedonia",
          capital: "Skopje",
          longitude: 21.433333,
          latitude: 42,
          code: "MK",
          continent: "Europe"),
      "Madagascar": Country(
          id: "127",
          name: "Madagascar",
          capital: "Antananarivo",
          longitude: 47.516667,
          latitude: -18.916666666666668,
          code: "MG",
          continent: "Africa"),
      "Malawi": Country(
          id: "128",
          name: "Malawi",
          capital: "Lilongwe",
          longitude: 33.783333,
          latitude: -13.966666666666667,
          code: "MW",
          continent: "Africa"),
      "Malaysia": Country(
          id: "129",
          name: "Malaysia",
          capital: "Kuala Lumpur",
          longitude: 101.7,
          latitude: 3.1666666666666665,
          code: "MY",
          continent: "Asia"),
      "Maldives": Country(
          id: "130",
          name: "Maldives",
          capital: "Male",
          longitude: 73.5,
          latitude: 4.166666666666667,
          code: "MV",
          continent: "Asia"),
      "Mali": Country(
          id: "131",
          name: "Mali",
          capital: "Bamako",
          longitude: -8.0,
          latitude: 12.65,
          code: "ML",
          continent: "Africa"),
      "Malta": Country(
          id: "132",
          name: "Malta",
          capital: "Valletta",
          longitude: 14.5,
          latitude: 35.88333333333333,
          code: "MT",
          continent: "Europe"),
      "Marshall Islands": Country(
          id: "133",
          name: "Marshall Islands",
          capital: "Majuro",
          longitude: 171.383333,
          latitude: 7.1,
          code: "MH",
          continent: "Australia"),
      "Mauritania": Country(
          id: "134",
          name: "Mauritania",
          capital: "Nouakchott",
          longitude: -15.966667,
          latitude: 18.066666666666666,
          code: "MR",
          continent: "Africa"),
      "Mauritius": Country(
          id: "135",
          name: "Mauritius",
          capital: "Port Louis",
          longitude: 57.483333,
          latitude: -20.15,
          code: "MU",
          continent: "Africa"),
      "Mexico": Country(
          id: "136",
          name: "Mexico",
          capital: "Mexico City",
          longitude: -99.133333,
          latitude: 19.433333333333334,
          code: "MX",
          continent: "Central America"),
      "Moldova": Country(
          id: "137",
          name: "Moldova",
          capital: "Chisinau",
          longitude: 28.85,
          latitude: 47,
          code: "MD",
          continent: "Europe"),
      "Monaco": Country(
          id: "138",
          name: "Monaco",
          capital: "Monaco",
          longitude: 7.416667,
          latitude: 43.733333333333334,
          code: "MC",
          continent: "Europe"),
      "Mongolia": Country(
          id: "139",
          name: "Mongolia",
          capital: "Ulaanbaatar",
          longitude: 106.916667,
          latitude: 47.916666666666664,
          code: "MN",
          continent: "Asia"),
      "Montenegro": Country(
          id: "140",
          name: "Montenegro",
          capital: "Podgorica",
          longitude: 19.266667,
          latitude: 42.43333333333333,
          code: "ME",
          continent: "Europe"),
      "Montserrat": Country(
          id: "141",
          name: "Montserrat",
          capital: "Plymouth",
          longitude: -62.216667,
          latitude: 16.7,
          code: "MS",
          continent: "North America"),
      "Morocco": Country(
          id: "142",
          name: "Morocco",
          capital: "Rabat",
          longitude: -6.816667,
          latitude: 34.016666666666666,
          code: "MA",
          continent: "Africa"),
      "Mozambique": Country(
          id: "143",
          name: "Mozambique",
          capital: "Maputo",
          longitude: 32.583333,
          latitude: -25.95,
          code: "MZ",
          continent: "Africa"),
      "Myanmar": Country(
          id: "144",
          name: "Myanmar",
          capital: "Rangoon",
          longitude: 96.15,
          latitude: 16.8,
          code: "MM",
          continent: "Asia"),
      "Namibia": Country(
          id: "145",
          name: "Namibia",
          capital: "Windhoek",
          longitude: 17.083333,
          latitude: -22.566666666666666,
          code: "NA",
          continent: "Africa"),
      "Nauru": Country(
          id: "146",
          name: "Nauru",
          capital: "Yaren",
          longitude: 166.920867,
          latitude: -0.5477,
          code: "NR",
          continent: "Australia"),
      "Nepal": Country(
          id: "147",
          name: "Nepal",
          capital: "Kathmandu",
          longitude: 85.316667,
          latitude: 27.716666666666665,
          code: "NP",
          continent: "Asia"),
      "Netherlands": Country(
          id: "148",
          name: "Netherlands",
          capital: "Amsterdam",
          longitude: 4.916667,
          latitude: 52.35,
          code: "NL",
          continent: "Europe"),
      "New Caledonia": Country(
          id: "149",
          name: "New Caledonia",
          capital: "Noumea",
          longitude: 166.45,
          latitude: -22.266666666666666,
          code: "NC",
          continent: "Australia"),
      "New Zealand": Country(
          id: "150",
          name: "New Zealand",
          capital: "Wellington",
          longitude: 174.783333,
          latitude: -41.3,
          code: "NZ",
          continent: "Australia"),
      "Nicaragua": Country(
          id: "151",
          name: "Nicaragua",
          capital: "Managua",
          longitude: -86.25,
          latitude: 12.133333333333333,
          code: "NI",
          continent: "Central America"),
      "Niger": Country(
          id: "152",
          name: "Niger",
          capital: "Niamey",
          longitude: 2.116667,
          latitude: 13.516666666666667,
          code: "NE",
          continent: "Africa"),
      "Nigeria": Country(
          id: "153",
          name: "Nigeria",
          capital: "Abuja",
          longitude: 7.533333,
          latitude: 9.083333333333334,
          code: "NG",
          continent: "Africa"),
      "Niue": Country(
          id: "154",
          name: "Niue",
          capital: "Alofi",
          longitude: -169.916667,
          latitude: -19.016666666666666,
          code: "NU",
          continent: "Australia"),
      "Norfolk Island": Country(
          id: "155",
          name: "Norfolk Island",
          capital: "Kingston",
          longitude: 167.966667,
          latitude: -29.05,
          code: "NF",
          continent: "Australia"),
      "North Korea": Country(
          id: "156",
          name: "North Korea",
          capital: "Pyongyang",
          longitude: 125.75,
          latitude: 39.016666666666666,
          code: "KP",
          continent: "Asia"),
      "Northern Cyprus": Country(
          id: "157",
          name: "Northern Cyprus",
          capital: "North Nicosia",
          longitude: 33.366667,
          latitude: 35.183333,
          code: "NULL",
          continent: "Europe"),
      "Northern Mariana Islands": Country(
          id: "158",
          name: "Northern Mariana Islands",
          capital: "Saipan",
          longitude: 145.75,
          latitude: 15.2,
          code: "MP",
          continent: "Australia"),
      "Norway": Country(
          id: "159",
          name: "Norway",
          capital: "Oslo",
          longitude: 10.75,
          latitude: 59.916666666666664,
          code: "NO",
          continent: "Europe"),
      "Oman": Country(
          id: "160",
          name: "Oman",
          capital: "Muscat",
          longitude: 58.583333,
          latitude: 23.616666666666667,
          code: "OM",
          continent: "Asia"),
      "Pakistan": Country(
          id: "161",
          name: "Pakistan",
          capital: "Islamabad",
          longitude: 73.05,
          latitude: 33.68333333333333,
          code: "PK",
          continent: "Asia"),
      "Palau": Country(
          id: "162",
          name: "Palau",
          capital: "Melekeok",
          longitude: 134.633333,
          latitude: 7.483333333333333,
          code: "PW",
          continent: "Australia"),
      "Palestine": Country(
          id: "163",
          name: "Palestine",
          capital: "Jerusalem",
          longitude: 35.233333,
          latitude: 31.766666666666666,
          code: "PS",
          continent: "Asia"),
      "Panama": Country(
          id: "164",
          name: "Panama",
          capital: "Panama City",
          longitude: -79.533333,
          latitude: 8.966666666666667,
          code: "PA",
          continent: "Central America"),
      "Papua New Guinea": Country(
          id: "165",
          name: "Papua New Guinea",
          capital: "Port Moresby",
          longitude: 147.183333,
          latitude: -9.45,
          code: "PG",
          continent: "Australia"),
      "Paraguay": Country(
          id: "166",
          name: "Paraguay",
          capital: "Asuncion",
          longitude: -57.666667,
          latitude: -25.266666666666666,
          code: "PY",
          continent: "South America"),
      "Peru": Country(
          id: "167",
          name: "Peru",
          capital: "Lima",
          longitude: -77.05,
          latitude: -12.05,
          code: "PE",
          continent: "South America"),
      "Philippines": Country(
          id: "168",
          name: "Philippines",
          capital: "Manila",
          longitude: 120.966667,
          latitude: 14.6,
          code: "PH",
          continent: "Asia"),
      "Pitcairn Islands": Country(
          id: "169",
          name: "Pitcairn Islands",
          capital: "Adamstown",
          longitude: -130.083333,
          latitude: -25.066666666666666,
          code: "PN",
          continent: "Australia"),
      "Poland": Country(
          id: "170",
          name: "Poland",
          capital: "Warsaw",
          longitude: 21.0,
          latitude: 52.25,
          code: "PL",
          continent: "Europe"),
      "Portugal": Country(
          id: "171",
          name: "Portugal",
          capital: "Lisbon",
          longitude: -9.133333,
          latitude: 38.71666666666667,
          code: "PT",
          continent: "Europe"),
      "Puerto Rico": Country(
          id: "172",
          name: "Puerto Rico",
          capital: "San Juan",
          longitude: -66.116667,
          latitude: 18.466666666666665,
          code: "PR",
          continent: "North America"),
      "Qatar": Country(
          id: "173",
          name: "Qatar",
          capital: "Doha",
          longitude: 51.533333,
          latitude: 25.283333333333335,
          code: "QA",
          continent: "Asia"),
      "Republic of Congo": Country(
          id: "174",
          name: "Republic of Congo",
          capital: "Brazzaville",
          longitude: 15.283333,
          latitude: -4.25,
          code: "CG",
          continent: "Africa"),
      "Romania": Country(
          id: "175",
          name: "Romania",
          capital: "Bucharest",
          longitude: 26.1,
          latitude: 44.43333333333333,
          code: "RO",
          continent: "Europe"),
      "Russia": Country(
          id: "176",
          name: "Russia",
          capital: "Moscow",
          longitude: 37.6,
          latitude: 55.75,
          code: "RU",
          continent: "Europe"),
      "Rwanda": Country(
          id: "177",
          name: "Rwanda",
          capital: "Kigali",
          longitude: 30.05,
          latitude: -1.95,
          code: "RW",
          continent: "Africa"),
      "Saint Barthelemy": Country(
          id: "178",
          name: "Saint Barthelemy",
          capital: "Gustavia",
          longitude: -62.85,
          latitude: 17.883333333333333,
          code: "BL",
          continent: "North America"),
      "Saint Helena": Country(
          id: "179",
          name: "Saint Helena",
          capital: "Jamestown",
          longitude: -5.716667,
          latitude: -15.933333333333334,
          code: "SH",
          continent: "Africa"),
      "Saint Kitts and Nevis": Country(
          id: "180",
          name: "Saint Kitts and Nevis",
          capital: "Basseterre",
          longitude: -62.716667,
          latitude: 17.3,
          code: "KN",
          continent: "North America"),
      "Saint Lucia": Country(
          id: "181",
          name: "Saint Lucia",
          capital: "Castries",
          longitude: -61.0,
          latitude: 14,
          code: "LC",
          continent: "North America"),
      "Saint Martin": Country(
          id: "182",
          name: "Saint Martin",
          capital: "Marigot",
          longitude: -63.0822,
          latitude: 18.0731,
          code: "MF",
          continent: "North America"),
      "Saint Pierre and Miquelon": Country(
          id: "183",
          name: "Saint Pierre and Miquelon",
          capital: "Saint-Pierre",
          longitude: -56.183333,
          latitude: 46.766666666666666,
          code: "PM",
          continent: "Central America"),
      "Saint Vincent and the Grenadines": Country(
          id: "184",
          name: "Saint Vincent and the Grenadines",
          capital: "Kingstown",
          longitude: -61.216667,
          latitude: 13.133333333333333,
          code: "VC",
          continent: "Central America"),
      "Samoa": Country(
          id: "185",
          name: "Samoa",
          capital: "Apia",
          longitude: -171.766667,
          latitude: -13.816666666666666,
          code: "WS",
          continent: "Australia"),
      "San Marino": Country(
          id: "186",
          name: "San Marino",
          capital: "San Marino",
          longitude: 12.416667,
          latitude: 43.93333333333333,
          code: "SM",
          continent: "Europe"),
      "Sao Tome and Principe": Country(
          id: "187",
          name: "Sao Tome and Principe",
          capital: "Sao Tome",
          longitude: 6.733333,
          latitude: 0.3333333333333333,
          code: "ST",
          continent: "Africa"),
      "Saudi Arabia": Country(
          id: "188",
          name: "Saudi Arabia",
          capital: "Riyadh",
          longitude: 46.7,
          latitude: 24.65,
          code: "SA",
          continent: "Asia"),
      "Senegal": Country(
          id: "189",
          name: "Senegal",
          capital: "Dakar",
          longitude: -17.633333,
          latitude: 14.733333333333333,
          code: "SN",
          continent: "Africa"),
      "Serbia": Country(
          id: "190",
          name: "Serbia",
          capital: "Belgrade",
          longitude: 20.5,
          latitude: 44.833333333333336,
          code: "RS",
          continent: "Europe"),
      "Seychelles": Country(
          id: "191",
          name: "Seychelles",
          capital: "Victoria",
          longitude: 55.45,
          latitude: -4.616666666666667,
          code: "SC",
          continent: "Africa"),
      "Sierra Leone": Country(
          id: "192",
          name: "Sierra Leone",
          capital: "Freetown",
          longitude: -13.233333,
          latitude: 8.483333333333333,
          code: "SL",
          continent: "Africa"),
      "Singapore": Country(
          id: "193",
          name: "Singapore",
          capital: "Singapore",
          longitude: 103.85,
          latitude: 1.2833333333333332,
          code: "SG",
          continent: "Asia"),
      "Sint Maarten": Country(
          id: "194",
          name: "Sint Maarten",
          capital: "Philipsburg",
          longitude: -63.033333,
          latitude: 18.016666666666666,
          code: "SX",
          continent: "North America"),
      "Slovakia": Country(
          id: "195",
          name: "Slovakia",
          capital: "Bratislava",
          longitude: 17.116667,
          latitude: 48.15,
          code: "SK",
          continent: "Europe"),
      "Slovenia": Country(
          id: "196",
          name: "Slovenia",
          capital: "Ljubljana",
          longitude: 14.516667,
          latitude: 46.05,
          code: "SI",
          continent: "Europe"),
      "Solomon Islands": Country(
          id: "197",
          name: "Solomon Islands",
          capital: "Honiara",
          longitude: 159.95,
          latitude: -9.433333333333334,
          code: "SB",
          continent: "Australia"),
      "Somalia": Country(
          id: "198",
          name: "Somalia",
          capital: "Mogadishu",
          longitude: 45.333333,
          latitude: 2.066666666666667,
          code: "SO",
          continent: "Africa"),
      "Somaliland": Country(
          id: "199",
          name: "Somaliland",
          capital: "Hargeisa",
          longitude: 44.05,
          latitude: 9.55,
          code: "NULL",
          continent: "Africa"),
      "South Africa": Country(
          id: "200",
          name: "South Africa",
          capital: "Pretoria",
          longitude: 28.216667,
          latitude: -25.7,
          code: "ZA",
          continent: "Africa"),
      "South Georgia and South Sandwich Islands": Country(
          id: "201",
          name: "South Georgia and South Sandwich Islands",
          capital: "King Edward Point",
          longitude: -36.5,
          latitude: -54.283333,
          code: "GS",
          continent: "Antarctica"),
      "South Korea": Country(
          id: "202",
          name: "South Korea",
          capital: "Seoul",
          longitude: 126.983333,
          latitude: 37.55,
          code: "KR",
          continent: "Asia"),
      "South Sudan": Country(
          id: "203",
          name: "South Sudan",
          capital: "Juba",
          longitude: 31.616667,
          latitude: 4.85,
          code: "SS",
          continent: "Africa"),
      "Spain": Country(
          id: "204",
          name: "Spain",
          capital: "Madrid",
          longitude: -3.683333,
          latitude: 40.4,
          code: "ES",
          continent: "Europe"),
      "Sri Lanka": Country(
          id: "205",
          name: "Sri Lanka",
          capital: "Colombo",
          longitude: 79.833333,
          latitude: 6.916666666666667,
          code: "LK",
          continent: "Asia"),
      "Sudan": Country(
          id: "206",
          name: "Sudan",
          capital: "Khartoum",
          longitude: 32.533333,
          latitude: 15.6,
          code: "SD",
          continent: "Africa"),
      "Suriname": Country(
          id: "207",
          name: "Suriname",
          capital: "Paramaribo",
          longitude: -55.166667,
          latitude: 5.833333333333333,
          code: "SR",
          continent: "South America"),
      "Svalbard": Country(
          id: "208",
          name: "Svalbard",
          capital: "Longyearbyen",
          longitude: 15.633333,
          latitude: 78.21666666666667,
          code: "SJ",
          continent: "Europe"),
      "Swaziland": Country(
          id: "209",
          name: "Swaziland",
          capital: "Mbabane",
          longitude: 31.133333,
          latitude: -26.316666666666666,
          code: "SZ",
          continent: "Africa"),
      "Sweden": Country(
          id: "210",
          name: "Sweden",
          capital: "Stockholm",
          longitude: 18.05,
          latitude: 59.333333333333336,
          code: "SE",
          continent: "Europe"),
      "Switzerland": Country(
          id: "211",
          name: "Switzerland",
          capital: "Bern",
          longitude: 7.466667,
          latitude: 46.916666666666664,
          code: "CH",
          continent: "Europe"),
      "Syria": Country(
          id: "212",
          name: "Syria",
          capital: "Damascus",
          longitude: 36.3,
          latitude: 33.5,
          code: "SY",
          continent: "Asia"),
      "Taiwan": Country(
          id: "213",
          name: "Taiwan",
          capital: "Taipei",
          longitude: 121.516667,
          latitude: 25.033333333333335,
          code: "TW",
          continent: "Asia"),
      "Tajikistan": Country(
          id: "214",
          name: "Tajikistan",
          capital: "Dushanbe",
          longitude: 68.766667,
          latitude: 38.55,
          code: "TJ",
          continent: "Asia"),
      "Tanzania": Country(
          id: "215",
          name: "Tanzania",
          capital: "Dar es Salaam",
          longitude: 39.283333,
          latitude: -6.8,
          code: "TZ",
          continent: "Africa"),
      "Thailand": Country(
          id: "216",
          name: "Thailand",
          capital: "Bangkok",
          longitude: 100.516667,
          latitude: 13.75,
          code: "TH",
          continent: "Asia"),
      "The Gambia": Country(
          id: "217",
          name: "The Gambia",
          capital: "Banjul",
          longitude: -16.566667,
          latitude: 13.45,
          code: "GM",
          continent: "Africa"),
      "Timor-Leste": Country(
          id: "218",
          name: "Timor-Leste",
          capital: "Dili",
          longitude: 125.6,
          latitude: -8.583333333333334,
          code: "TL",
          continent: "Asia"),
      "Togo": Country(
          id: "219",
          name: "Togo",
          capital: "Lome",
          longitude: 1.216667,
          latitude: 6.116666666666666,
          code: "TG",
          continent: "Africa"),
      "Tokelau": Country(
          id: "220",
          name: "Tokelau",
          capital: "Atafu",
          longitude: -171.833333,
          latitude: -9.166667,
          code: "TK",
          continent: "Australia"),
      "Tonga": Country(
          id: "221",
          name: "Tonga",
          capital: "Nuku'alofa",
          longitude: -175.2,
          latitude: -21.133333333333333,
          code: "TO",
          continent: "Australia"),
      "Trinidad and Tobago": Country(
          id: "222",
          name: "Trinidad and Tobago",
          capital: "Port of Spain",
          longitude: -61.516667,
          latitude: 10.65,
          code: "TT",
          continent: "North America"),
      "Tunisia": Country(
          id: "223",
          name: "Tunisia",
          capital: "Tunis",
          longitude: 10.183333,
          latitude: 36.8,
          code: "TN",
          continent: "Africa"),
      "Turkey": Country(
          id: "224",
          name: "Turkey",
          capital: "Ankara",
          longitude: 32.866667,
          latitude: 39.93333333333333,
          code: "TR",
          continent: "Europe"),
      "Turkmenistan": Country(
          id: "225",
          name: "Turkmenistan",
          capital: "Ashgabat",
          longitude: 58.383333,
          latitude: 37.95,
          code: "TM",
          continent: "Asia"),
      "Turks and Caicos Islands": Country(
          id: "226",
          name: "Turks and Caicos Islands",
          capital: "Grand Turk",
          longitude: -71.133333,
          latitude: 21.466666666666665,
          code: "TC",
          continent: "North America"),
      "Tuvalu": Country(
          id: "227",
          name: "Tuvalu",
          capital: "Funafuti",
          longitude: 179.216667,
          latitude: -8.516666666666667,
          code: "TV",
          continent: "Australia")
    });
