name: interactive_world_map
description: This was a first go at creating an interactive map component

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  vector_map:
  flutter_riverpod: ^2.6.1
  freezed: ^2.5.8
  freezed_annotation: ^2.4.4
  geolocator: ^9.0.2
  desktop_webview_auth: ^0.0.15
  date_time_picker:
    git:
      url: https://github.com/tmcmaster/date_time_picker.git
  wt_app_scaffold:
    git:
      url: https://github.com/tmcmaster/wt_app_scaffold.git
  wt_models:
    git:
      url: git@github.com:tmcmaster/wt_models.git
  wt_logging:
    git:
      url: git@github.com:tmcmaster/wt_logging.git
  wt_settings:
    git:
      url: git@github.com:tmcmaster/wt_settings.git

dependency_overrides:
  date_time_picker:
    path: ../../../../fork/date_time_picker
  wt_app_scaffold:
    path: ../../../../libraries/wt_app_scaffold
  wt_logging:
    path: ../../../../libraries/wt_logging
  wt_models:
    path: ../../../../libraries/wt_models
  wt_settings:
    path: ../../../../libraries/wt_settings
